version: "3"
services:
  serverstatus:
    build:
      context: .
      dockerfile: Dockerfile
    image: serverstatus_server
    container_name: serverstatus
    restart: unless-stopped
    volumes:
      - ./server/config.json:/ServerStatus/server/config.json 
      - ./web/json:/usr/share/nginx/html/json
    ports:
      - 443:35601
      - 8080:80
    networks:
      - serverstatus-network

networks:
  serverstatus-network:
    name: serverstatus-network
